import { formatDateRange } from "./utils";

import marmaladeImg from "../assets/showcase/marmalade.webp";
import loloImg from "../assets/showcase/lolo.webp";
import orchestorImg from "../assets/showcase/orchestor.webp";
import recessImg from "../assets/showcase/recess.webp";
import poopoovilleImg from "../assets/showcase/poopooville.webp";
import bimTranslatorImg from "../assets/showcase/bim-translator.webp";

export default {
	name: "Rahman Nurudin",
	about: `Building end-to-end production systems. I combine high-performance frontend engineering with backend architectures that hold under load, including chat platforms, background workers, AI pipelines, caching layers, and event-driven workflows.`,
	location: "Tangerang, Indonesia",
	profession: "Full Stack Engineer",
	contactEmail: "rahwisdilfiqrak@gmail.com",
	meta: {
		title: "Rahman Nurudin | Full Stack Engineer",
		description:
			"Full Stack Developer | React, Next.js, NestJS, PostgreSQL, Redis",
		favicon: "https://avatars.githubusercontent.com/u/93178373?size=64",
	},
	social: {
		github: "TraFost",
		discord: "rahmannrdn",
		instagram: "rahmannrdn",
	},
	projects: [
		{
			title: "Ruang Diri",
			description: `Professional counseling platform with real-time chat, session automation, file uploads, and search. Modular backend supports multiple roles and B2B deployments with strict access control and real-time delivery.`,
			thumbnail: "https://i.postimg.cc/HxFL10KN/showcase-3.webp",
			tags: [
				"NestJS",
				"TypeScript",
				"PostgreSQL",
				"Google Cloud Run",
				"Google Cloud Storage",
				"Resend",
				"Zoom API",
				"Socket.io",
				"Drizzle ORM",
				"Redis",
				"BullMQ",
				"Ably",
				"React",
			],
			isPrivate: true,
		},
		{
			title: "Marmalade – Voice-First Emotional Companion",
			description: `Real-time voice AI companion delivering safe, clinically aligned emotional support. Built a speculative execution pipeline, custom OpenAI-compatible interface, and contextual memory engine for low-latency, stateful interactions.`,
			thumbnail: marmaladeImg,
			tags: [
				"React",
				"Hono",
				"Google Cloud Run",
				"PostgreSQL",
				"Text-Embedding-005",
				"Drizzle ORM",
				"Vertex AI",
				"ElevenLabs",
				"ElevenLabs Conversational Agents",
				"Pulumi",
				"Gemini 2.5 Flash",
				"Gemini 2.5 Pro",
			],
			url: "https://devpost.com/software/marmalade-lq2rd1?ref_content=my-projects-tab&ref_feature=my_projects",
			repository: "https://github.com/TraFost/Marmalade",
		},
		{
			title: "LoLo – AI League Coach",
			description: `Serverless AI companion converting raw LoL match data into coaching insights. Managed full-stack Turbo Monorepo, JSON-only architecture, graceful degradation, and social card generation for low-latency, reliable guidance.`,
			thumbnail: loloImg,
			tags: [
				"React",
				"TypeScript",
				"Hono",
				"AWS Lambda",
				"SST",
				"Amazon Bedrock",
				"AWS S3",
				"TanStack Query",
				"Tailwind",
				"ShadCN",
			],
			url: "https://devpost.com/software/helfer?ref_content=my-projects-tab&ref_feature=my_projects",
			repository: "https://github.com/TraFost/LoLo",
		},
		{
			title: "Orchestor – Agentic Social Media Scheduler",
			description: `AI system transforming Asana tasks into validated schedules and repost suggestions. Built backend, integrated IBM watsonx Orchestrate, and ensured stable, machine-readable JSON output.`,
			thumbnail: orchestorImg,
			tags: [
				"React",
				"Hono",
				"Cloudflare Workers",
				"TypeScript",
				"IBM watsonx Orchestrate",
			],
			url: "https://lablab.ai/event/agentic-ai-hackathon-ibm-watsonx-orchestrate/agentbunnies/orchestor",
			repository: "https://github.com/TraFost/orchestor-be",
		},
		{
			title: "Recess – Production Platform",
			description: `Role-based production management platform for quoting, project planning, collaboration, and staged payouts. Built RLS-first PostgreSQL schemas, audit logs, multi-step approvals, and secure file uploads via Supabase Edge Functions to Wasabi.`,
			thumbnail: recessImg,
			tags: [
				"React",
				"Supabase",
				"PostgreSQL",
				"Edge Functions",
				"Wasabi",
				"RLS",
				"Real-time Collaboration",
			],
			isPrivate: true,
		},
		{
			title: "Poopooville – Web3 Ecosystem",
			description: `Multi-chain dApp on Ethereum & BSC supporting NFT minting, token sales, and vesting/claim flows. Integrated wallet connections via Wagmi, Viem, and Reown AppKit, maintaining sync across frontend, backend, and on-chain state.`,
			thumbnail: poopoovilleImg,
			tags: [
				"React",
				"Vite",
				"Ethereum",
				"BSC",
				"Wagmi",
				"Viem",
				"Reown AppKit",
				"Web3",
				"NFT",
				"Token Sale",
			],
			isPrivate: true,
		},
		{
			title: "BIMTranslator",
			description:
				"Hackathon project with in-browser translation of Malaysian Sign Language gestures to text, using MediaPipe hand landmarks, TensorFlow.js classification, phrase matching, and animation playback.",
			thumbnail: bimTranslatorImg,
			tags: [
				"React",
				"TypeScript",
				"MediaPipe",
				"TensorFlow.js",
				"TailwindCSS",
				"Framer Motion",
			],
			url: "https://bim-translator-l4md.vercel.app",
			repository: "https://github.com/TraFost/bim-translator",
			isPrivate: false,
		},
		{
			title: "Honcho Dashboard",
			description: `Honcho Dashboard is a web application that allows users to manage their account, albums, and view their photos. It also allows users to share their albums with others.`,
			thumbnail: "https://i.postimg.cc/QMxCQd1f/showcase-4.webp",
			tags: [
				"Typescript",
				"Material-UI",
				"Next.js",
				"React Query",
				"Rx.js",
				"Firebase",
				"Jotai",
				"Websockets",
				"AWS",
				"Docker",
			],
			url: "https://dashboard.thehoncho.app/login",
			isPrivate: true,
		},
		{
			title: "Honcho Public",
			description: `Honcho public is a real-time event photo platform that lets users view and download photos from events. It features a live slideshow, live album, real-time photo uploads, and analytics.`,
			thumbnail: "https://i.postimg.cc/d1h0fNWd/showcase-5.webp",
			tags: [
				"Typescript",
				"Material-UI",
				"Next.js",
				"React Query",
				"Rx.js",
				"Firebase",
				"Jotai",
				"Websockets",
				"AWS",
				"Docker",
			],
			url: "https://public.thehoncho.app/album/671dfade6f172a4857be19e6?type=all",
			isPrivate: true,
		},
		{
			title: "KTA Buya Pasaman Timur",
			description:
				"A digital membership card mobile application for the East Pasaman Buya Members. Features include event registration, digital card, and member profile management.",
			thumbnail: "https://i.postimg.cc/QMxCQd1f/showcase-4.webp",
			tags: ["React Native", "Typescript", "Zustand"],
			url: "https://play.google.com/store/apps/details?id=com.bpt_app&hl=en_US&pli=1",
			isPrivate: false,
		},
	],
	technologies: [
		{
			name: "Typescript",
			slug: "typescript",
		},
		{ name: "Javascript", slug: "javascript" },
		{ name: "React", slug: "react" },
		{ name: "React Native", slug: "react" },
		{ name: "Next.js", slug: "nextjs" },
		{ name: "NestJS", slug: "nestjs" },
		{ name: "Node.js", slug: "nodejs" },
		{ name: "Express", slug: "express" },
		{ name: "PostgreSQL", slug: "postgresql" },
		{ name: "Redis", slug: "redis" },
		{ name: "Google Cloud", slug: "googlecloud" },
		{
			name: "AWS",
			slug: "amazonwebservices",
			extendedSlug: "amazonwebservices-original-wordmark",
		},
		{ name: "Docker", slug: "docker" },
		{ name: "Firebase", slug: "firebase" },
		{ name: "Socket.io", slug: "socketio" },
		{ name: "Tailwind", slug: "tailwindcss" },
		{ name: "Redux", slug: "redux" },
		{ name: "Jest", slug: "jest", extendedSlug: "jest-plain" },
		{ name: "Rx.js", slug: "rxjs" },
		{ name: "Material-UI", slug: "materialui" },
	],
	experiences: [
		{
			title: "Fullstack Engineer (Independent / Contract)",
			company: "Recess & Poopooville",
			year: "November 2025 – Present | Remote",
			description:
				"Built a role-based production platform for project management, quoting, collaboration, and staged payouts, and contributed to a multi-chain Web3 ecosystem with NFTs, token sales, and on-chain interactions.",
			duration: formatDateRange("2025-11-01", "Present"),
			responsibilities: [
				"Built a role-based production management platform on Supabase for quoting, project planning, real-time collaboration, and staged payouts.",
				"Designed RLS-first PostgreSQL schemas with multi-step approvals, audit logs, and role-scoped access.",
				"Implemented secure file uploads via Supabase Edge Functions, proxying to Wasabi with signed URL caching.",
				"Contributed to frontend and Web3 integrations for a multi-chain dApp (Ethereum & BSC), including NFT minting, token sales, and vesting/claim flows.",
				"Integrated wallet connections using Wagmi, Viem, and Reown AppKit across multiple networks.",
				"Maintained and optimized a large React/Vite codebase with synchronized on-chain, backend, and UI state.",
			],
		},
		{
			title: "Fullstack Developer",
			company: "PT. Wong Makmur Sejati",
			year: "April 2025 – November 2025 | South Jakarta, Indonesia",
			description:
				"Scaling a counseling platform with secure APIs and real-time collaboration for mental wellness teams.",
			duration: formatDateRange("2025-04-01", "2025-11-01"),
			responsibilities: [
				"Designed and deployed secure NestJS + PostgreSQL (Drizzle ORM) APIs serving 5,000+ monthly counseling and scheduling requests.",
				"Built Ably-powered chat (presence, file sharing, unread tracking, search) supporting hundreds of active users daily while keeping message latency under 200ms.",
				"Automated Zoom session setup and notifications with Bull + Redis, saving the team 10+ hours of manual coordination every week.",
				"Developed prioritized Bull + Redis job queues with retry logic, processing hundreds of background tasks daily at 99% reliability.",
				"Integrated Google Cloud Storage, Resend email delivery, and Puppeteer PDF generation to create reports and file operations.",
			],
		},
		{
			title: "Frontend Web Developer",
			company: "Ubersnap Pte. Ltd.",
			year: "October 2024 – April 2025 | Singapore (Remote)",
			description:
				"Shipped high-performing marketing and product experiences for a global photo platform.",
			duration: formatDateRange("2024-10-01", "2025-04-10"),
			responsibilities: [
				"Implemented optimistic updates, polling, and queuing to keep complex dashboards responsive for 1,000+ daily active users.",
				"Boosted Lighthouse scores from the 70s to 90+, driving a 15% lift in organic traffic.",
				"Increased user engagement by 25% through targeted UI improvements and faster load times across web and mobile.",
				"Partnered with design, backend, and QA teams across three time zones to ship features under shifting requirements.",
				"Expanded unit and regression test coverage, cutting post-release bugs by 30% and improving long-term stability.",
			],
		},
		{
			title: "Frontend Developer (Web & Mobile)",
			company: "PT. Healstation Indonesia",
			year: "April 2023 – October 2024 | Jakarta, Indonesia (Hybrid)",
			description:
				"Delivering healthcare, POS, and CMS products across web and mobile for Korean clients.",
			duration: formatDateRange("2023-04-01", "2024-10-01"),
			responsibilities: [
				"Delivered 7+ production apps across healthcare, POS, and CMS domains serving 5,000+ end users.",
				"Built shared React, Next.js, and React Native codebases to accelerate delivery and cut duplicate logic by 40%.",
				"Maintained 95%+ cross-device and browser compatibility to ensure consistent experiences.",
				"Partnered with leadership to align delivery with business goals, reducing bottlenecks across squads.",
				"Implemented Socket.io and Firebase real-time updates that reduced POS order delays by 60% and improved satisfaction.",
			],
		},
	],
	educations: [
		{
			title: "B.Sc. Informatics Engineering (GPA 3.70/4.0)",
			school: "Universitas Muhammadiyah Tangerang",
			year: "2021 - 2025",
		},
		{
			title: "English First (EF)",
			school: "EF",
			year: "2024 - 2025",
		},
		{
			title: "Fullstack Bootcamp Developer",
			school: "Harisenin",
			year: "2022 - 2023",
		},
	],
};
